- name: Ensure directory exist
  ansible.builtin.file:
    path: /etc/security
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Deploy the configured pwquality.conf
  ansible.builtin.template:
    src: "pwquality.conf.j2"
    dest: "/etc/security/pwquality.conf"